
class InfoPanel {
    constructor() {
        this.topics = {
            'Event Horizon': {
                title: 'Event Horizon',
                description: 'The boundary around a black hole beyond which nothing can escape, not even light. It marks the point of no return.',
                details: [
                    'Radius depends on black hole mass (Schwarzschild radius)',
                    'Time dilation becomes infinite at the horizon',
                    'Information paradox: what happens to information that falls in?'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Event_horizon',
                    'https://www.nasa.gov/audience/forstudents/k-4/stories/nasa-knows/what-is-a-black-hole-k4.html'
                ]
            },
            'Accretion Disk': {
                title: 'Accretion Disk',
                description: 'A rotating disk of matter spiraling into the black hole, heated to millions of degrees and glowing brightly.',
                details: [
                    'Material heats up due to friction and gravitational compression',
                    'Inner edge temperature can reach 10^7 Kelvin',
                    'Source of most observable light from black hole systems'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Accretion_disk',
                    'https://www.eso.org/public/outreach/eduoff/aol/market/experiments/blackhole/'
                ]
            },
            'Relativistic Jets': {
                title: 'Relativistic Jets',
                description: 'High-energy plasma beams ejected from the poles of rotating black holes at near light-speed.',
                details: [
                    'Powered by magnetic field interactions',
                    'Can extend thousands of light-years',
                    'Exhibit relativistic beaming and Doppler shifting'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Relativistic_jet',
                    'https://www.nasa.gov/mission_pages/nustar/news/nustar20140820.html'
                ]
            },
            'Magnetic Fields': {
                title: 'Magnetic Fields',
                description: 'Powerful magnetic field lines that thread through the accretion disk and help launch jets.',
                details: [
                    'Generated by rotating charged plasma',
                    'Key mechanism for jet formation (Blandford-Znajek process)',
                    'Can be twisted and amplified by frame-dragging'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Magnetosphere',
                    'https://iopscience.iop.org/article/10.1088/0004-637X/697/2/1681'
                ]
            },
            'Gravitational Lensing': {
                title: 'Gravitational Lensing',
                description: 'The bending of light around massive objects, creating distorted and multiple images of background sources.',
                details: [
                    'Predicted by Einstein\'s General Relativity',
                    'Creates Einstein rings and photon spheres',
                    'Allows us to see behind the black hole'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Gravitational_lensing',
                    'https://hubblesite.org/contents/articles/gravitational-lensing'
                ]
            },
            'Frame Dragging': {
                title: 'Frame Dragging',
                description: 'The twisting of spacetime around a rotating black hole, dragging nearby objects along.',
                details: [
                    'Also known as the Lense-Thirring effect',
                    'Causes orbital precession around rotating masses',
                    'Measured by Gravity Probe B satellite'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Frame-dragging',
                    'https://www.nasa.gov/mission_pages/gpb/overview/index.html'
                ]
            },
            'Time Dilation': {
                title: 'Gravitational Time Dilation',
                description: 'Time slows down in stronger gravitational fields, approaching zero at the event horizon.',
                details: [
                    'Consequence of General Relativity',
                    'Clocks run slower closer to massive objects',
                    'GPS satellites must account for this effect'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Gravitational_time_dilation',
                    'https://www.einstein-online.info/elementary/generalRT/time_dilation'
                ]
            },
            'Hawking Radiation': {
                title: 'Hawking Radiation',
                description: 'Theoretical thermal radiation emitted by black holes due to quantum effects near the event horizon.',
                details: [
                    'Temperature inversely proportional to mass',
                    'Causes black holes to slowly evaporate',
                    'Leads to the information paradox'
                ],
                sources: [
                    'https://en.wikipedia.org/wiki/Hawking_radiation',
                    'https://www.scientificamerican.com/article/the-black-hole-information-paradox/'
                ]
            }
        };
        
        this.createPanel();
        this.setupEventListeners();
    }

    createPanel() {
        const panel = document.createElement('div');
        panel.id = 'info-panel';
        panel.className = 'info-panel';
        
        const title = document.createElement('h3');
        title.textContent = 'Physics Topics';
        title.className = 'panel-title';
        panel.appendChild(title);

        const topicsList = document.createElement('div');
        topicsList.className = 'topics-list';
        
        Object.keys(this.topics).forEach(topicKey => {
            const topicItem = document.createElement('div');
            topicItem.className = 'topic-item';
            topicItem.textContent = topicKey;
            topicItem.dataset.topic = topicKey;
            topicsList.appendChild(topicItem);
        });
        
        panel.appendChild(topicsList);
        document.body.appendChild(panel);

        // Create popup container
        const popup = document.createElement('div');
        popup.id = 'topic-popup';
        popup.className = 'topic-popup hidden';
        popup.innerHTML = `
            <div class="popup-content">
                <div class="popup-header">
                    <h4 class="popup-title"></h4>
                    <button class="popup-close">×</button>
                </div>
                <div class="popup-body">
                    <p class="popup-description"></p>
                    <ul class="popup-details"></ul>
                    <div class="popup-sources">
                        <h5>Sources:</h5>
                        <ul class="sources-list"></ul>
                    </div>
                </div>
            </div>
        `;
        document.body.appendChild(popup);
    }

    setupEventListeners() {
        // Topic item clicks
        document.addEventListener('click', (event) => {
            if (event.target.classList.contains('topic-item')) {
                const topicKey = event.target.dataset.topic;
                this.showPopup(topicKey);
            }
        });

        // Close popup
        document.addEventListener('click', (event) => {
            if (event.target.classList.contains('popup-close') || 
                event.target.id === 'topic-popup') {
                this.hidePopup();
            }
        });

        // ESC key to close popup
        document.addEventListener('keydown', (event) => {
            if (event.key === 'Escape') {
                this.hidePopup();
            }
        });
    }

    showPopup(topicKey) {
        const topic = this.topics[topicKey];
        const popup = document.getElementById('topic-popup');
        
        popup.querySelector('.popup-title').textContent = topic.title;
        popup.querySelector('.popup-description').textContent = topic.description;
        
        const detailsList = popup.querySelector('.popup-details');
        detailsList.innerHTML = '';
        topic.details.forEach(detail => {
            const li = document.createElement('li');
            li.textContent = detail;
            detailsList.appendChild(li);
        });
        
        const sourcesList = popup.querySelector('.sources-list');
        sourcesList.innerHTML = '';
        topic.sources.forEach(source => {
            const li = document.createElement('li');
            const link = document.createElement('a');
            link.href = source;
            link.target = '_blank';
            link.textContent = this.getDomainName(source);
            li.appendChild(link);
            sourcesList.appendChild(li);
        });
        
        popup.classList.remove('hidden');
    }

    hidePopup() {
        document.getElementById('topic-popup').classList.add('hidden');
    }

    getDomainName(url) {
        try {
            return new URL(url).hostname;
        } catch {
            return url;
        }
    }
}

// Initialize when page loads
document.addEventListener('DOMContentLoaded', () => {
    new InfoPanel();
});
